import { Router } from "express";

const router = Router();

import * as codesCtrl from '../controllers/code.controller';
import { authJwt } from '../middlewares';

/**
 * @swagger
 * tags:
 *   name: Codes
 *   description: Urbanización access and visitor code management
 */

/**
 * @swagger
 * /api/codes:
 *   post:
 *     summary: Store a new visitor access code generated by client app
 *     tags: [Codes]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - code
 *             properties:
 *               code: 
 *                 type: string
 *                 description: Encrypted string code generated by client app
 *               name: 
 *                 type: string
 *               status:
 *                 type: boolean
 *               user:
 *                 type: array
 *                 items:
 *                   type: string
 *                 description: User ID or email of resident issuing the code
 *               recipientUser:
 *                 type: string
 *                 description: User ID of guest recipient (if already registered)
 *               location:
 *                 type: array
 *                 items:
 *                   type: string
 *                 description: Location IDs or names authorized for entry
 *               validFrom:
 *                 type: string
 *                 format: date-time
 *               validUntil:
 *                 type: string
 *                 format: date-time
 *               guestName:
 *                 type: string
 *               guestIdentification:
 *                 type: string
 *               guestMobile:
 *                 type: string
 *                 description: Contact phone number of guest
 *               guestEmail:
 *                 type: string
 *                 description: Contact email of guest
 *               vehiclePlate:
 *                 type: string
 *     responses:
 *       201:
 *         description: The code was successfully created
 *       400:
 *         description: Bad request (missing code or duplicate)
 *       500:
 *         description: Internal server error
 */
router.post('/', [authJwt.verifyToken], codesCtrl.createCode);

/**
 * @swagger
 * /api/codes:
 *   get:
 *     summary: Get all visitor codes
 *     tags: [Codes]
 *     responses:
 *       200:
 *         description: A list of visitor codes
 *       500:
 *         description: Internal server error
 */
router.get('/', codesCtrl.getCodes);

/**
 * @swagger
 * /api/codes/received:
 *   get:
 *     summary: Get access codes received by current authenticated guest user
 *     tags: [Codes]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: List of codes received by current user
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Internal server error
 */
router.get('/received', [authJwt.verifyToken], codesCtrl.getReceivedCodes);

/**
 * @swagger
 * /api/codes/sent:
 *   get:
 *     summary: Get access codes sent/issued by current authenticated resident user
 *     tags: [Codes]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: List of codes sent by current user
 *       401:
 *         description: Unauthorized
 *       500:
 *         description: Internal server error
 */
router.get('/sent', [authJwt.verifyToken], codesCtrl.getSentCodes);

/**
 * @swagger
 * /api/codes/verify:
 *   post:
 *     summary: Verify code access at a reader location (garita)
 *     tags: [Codes]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - code
 *             properties:
 *               code:
 *                 type: string
 *                 description: Encrypted code string scanned at location
 *               locationId:
 *                 type: string
 *                 description: ID of location/garita where reader is installed
 *               locationName:
 *                 type: string
 *                 description: Name of location/garita
 *     responses:
 *       200:
 *         description: Access granted
 *       403:
 *         description: Access denied (expired, inactive, or location unauthorized)
 *       404:
 *         description: Code not found
 *       500:
 *         description: Internal server error
 */
router.post('/verify', codesCtrl.verifyAccess);

/**
 * @swagger
 * /api/codes/user/{userId}:
 *   get:
 *     summary: Get access codes issued by a specific resident user
 *     tags: [Codes]
 *     parameters:
 *       - in: path
 *         name: userId
 *         schema:
 *           type: string
 *         required: true
 *         description: Resident user ID
 *     responses:
 *       200:
 *         description: List of codes belonging to user
 *       500:
 *         description: Internal server error
 */
router.get('/user/:userId', codesCtrl.getCodesByUser);

/**
 * @swagger
 * /api/codes/{codeId}:
 *   get:
 *     summary: Get a code by ID
 *     tags: [Codes]
 *     parameters:
 *       - in: path
 *         name: codeId
 *         schema:
 *           type: string
 *         required: true
 *         description: The code record ID
 *     responses:
 *       200:
 *         description: Details of the code
 *       404:
 *         description: Code not found
 *       500:
 *         description: Internal server error
 */
router.get('/:codeId', codesCtrl.getCodeById);

/**
 * @swagger
 * /api/codes/{codeId}:
 *   put:
 *     summary: Update a code by ID
 *     tags: [Codes]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: codeId
 *         schema:
 *           type: string
 *         required: true
 *         description: The code ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               status:
 *                 type: boolean
 *               validUntil:
 *                 type: string
 *                 format: date-time
 *     responses:
 *       200:
 *         description: Code updated successfully
 *       404:
 *         description: Code not found
 *       500:
 *         description: Internal server error
 */
router.put('/:codeId', [authJwt.verifyToken, authJwt.isAdmin], codesCtrl.updateCodeById);

/**
 * @swagger
 * /api/codes/{codeId}:
 *   delete:
 *     summary: Delete/revoke a code by ID
 *     tags: [Codes]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: codeId
 *         schema:
 *           type: string
 *         required: true
 *         description: The code ID
 *     responses:
 *       204:
 *         description: Code deleted
 *       404:
 *         description: Code not found
 *       500:
 *         description: Internal server error
 */
router.delete('/:codeId', [authJwt.verifyToken, authJwt.isAdmin], codesCtrl.deleteCodeById);

export default router;